//! Renders a parsed [`Dictionary`] to a Rust source file consumed by
//! the `radius-dict` crate's `generated` module.
//!
//! Used by `build.rs` at compile time and by the in-tree determinism /
//! snapshot tests. Output is deterministic: the parser preserves source
//! order, this renderer is a pure function of its input, and no
//! timestamps or absolute paths leak in.

use std::fmt::Write;

use super::{Dictionary, Flags, Type};

/// Render `dict` to a string suitable for `include!()` inside a module
/// rooted one level below `crate::dict` (so `super::Type::Foo` resolves).
///
/// `module_label` is embedded in the file header comment for human
/// orientation and has no semantic effect.
#[must_use]
pub fn render(module_label: &str, dict: &Dictionary) -> String {
    let mut out = String::with_capacity(estimate_capacity(dict));

    writeln!(
        out,
        "// @generated by build.rs from FreeRADIUS dictionary group `{module_label}`."
    )
    .unwrap();
    writeln!(
        out,
        "// Do not edit by hand; rerun `cargo build` to refresh."
    )
    .unwrap();
    writeln!(out).unwrap();

    write_vendors(&mut out, dict);
    writeln!(out).unwrap();
    write_attributes(&mut out, dict);
    writeln!(out).unwrap();
    write_values(&mut out, dict);
    writeln!(out).unwrap();
    write_attrs_module(&mut out, dict);

    out
}

fn write_vendors(out: &mut String, dict: &Dictionary) {
    writeln!(out, "pub static VENDORS: &[VendorEntry] = &[").unwrap();
    for v in &dict.vendors {
        writeln!(
            out,
            "    VendorEntry {{ name: {name:?}, id: {id}, type_len: {type_len}, length_len: {length_len}, has_continuation: {cont} }},",
            name = v.name,
            id = v.id,
            type_len = v.type_len,
            length_len = v.length_len,
            cont = v.has_continuation,
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn write_attributes(out: &mut String, dict: &Dictionary) {
    writeln!(out, "pub static ATTRIBUTES: &[AttributeEntry] = &[").unwrap();
    for a in &dict.attributes {
        let vendor = match a.vendor {
            Some(v) => format!("Some({v})"),
            None => "None".to_owned(),
        };
        let typ = match a.typ {
            Type::FixedOctets(n) => format!("super::Type::FixedOctets({n})"),
            other => type_literal(other).to_owned(),
        };
        writeln!(
            out,
            "    AttributeEntry {{ name: {name:?}, oid: &{oid}, vendor: {vendor}, typ: {typ}, flags: {flags} }},",
            name = a.name,
            oid = oid_literal(&a.oid.0),
            flags = flags_literal(a.flags),
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn write_values(out: &mut String, dict: &Dictionary) {
    writeln!(out, "pub static VALUES: &[ValueEntry] = &[").unwrap();
    for v in &dict.values {
        writeln!(
            out,
            "    ValueEntry {{ attribute: {attr:?}, name: {name:?}, number: {n} }},",
            attr = v.attribute,
            name = v.name,
            n = v.number,
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

/// Emit `pub mod attrs { ... }` with one typed const per attribute.
///
/// Top-level attributes become `Attr<T>`; vendor attributes become
/// `VsaAttr<T>`. Children with multi-component OIDs (TLV / extended
/// children) are skipped — they need a navigation API the codec does
/// not yet expose. Each emitted const inherits its `T` from the
/// dictionary's wire type via [`wire_marker`].
fn write_attrs_module(out: &mut String, dict: &Dictionary) {
    writeln!(
        out,
        "/// Typed handles for every attribute in this dictionary group."
    )
    .unwrap();
    writeln!(out, "///").unwrap();
    writeln!(
        out,
        "/// Top-level attributes are exposed as `Attr<T>`; attributes inside a"
    )
    .unwrap();
    writeln!(
        out,
        "/// `BEGIN-VENDOR` block are exposed as `VsaAttr<T>`. Use them with"
    )
    .unwrap();
    writeln!(
        out,
        "/// `RawAttribute::get` / `RawAttribute::get_vsa` (in `radius_tokio::attributes`)."
    )
    .unwrap();
    writeln!(
        out,
        "#[allow(missing_docs, unused_imports, clippy::wildcard_imports)]"
    )
    .unwrap();
    writeln!(out, "pub mod attrs {{").unwrap();
    writeln!(out, "    use crate::typed::*;").unwrap();
    writeln!(out).unwrap();
    for a in &dict.attributes {
        // Sub-attributes need a TLV walker; skip until that lands.
        if a.oid.0.len() != 1 {
            continue;
        }
        let Ok(code) = u8::try_from(a.oid.0[0]) else {
            // Out-of-range top-level codes (shouldn't happen in any
            // current dictionary, but guard anyway).
            continue;
        };
        let marker = wire_marker(a.typ);
        let ident = const_ident(&a.name);
        match a.vendor {
            None => writeln!(
                out,
                "    pub const {ident}: Attr<{marker}> = Attr::new({code});",
            )
            .unwrap(),
            Some(pen) => writeln!(
                out,
                "    pub const {ident}: VsaAttr<{marker}> = VsaAttr::new({pen}, {code});",
            )
            .unwrap(),
        }
    }
    writeln!(out, "}}").unwrap();
}

/// Convert a dictionary attribute name (`Cisco-AVPair`) into a Rust
/// constant identifier (`CISCO_AVPAIR`). Replaces `-` with `_` and
/// upper-cases ASCII letters; non-ASCII bytes pass through unchanged.
fn const_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        match ch {
            '-' => out.push('_'),
            c if c.is_ascii_lowercase() => out.push(c.to_ascii_uppercase()),
            c => out.push(c),
        }
    }
    out
}

/// Map a dictionary [`Type`] to the codec wire-type marker that decodes
/// it. Container / extended types fall back to [`WBytes`]: callers get
/// the raw value octets and can drill in with a future TLV walker.
fn wire_marker(t: Type) -> &'static str {
    match t {
        Type::String => "WText",
        Type::Byte => "WByte",
        Type::Short => "WShort",
        Type::Integer | Type::Uint32 | Type::Date => "WInteger",
        Type::Integer64 => "WInteger64",
        Type::Signed => "WSigned",
        Type::Ipaddr => "WIpv4",
        Type::Ipv6addr => "WIpv6",
        Type::Ether => "WEther",
        Type::Ifid => "WIfid",
        // Container / variable-shape types decode as raw octets for now.
        Type::Octets
        | Type::FixedOctets(_)
        | Type::Abinary
        | Type::Ipv4prefix
        | Type::Ipv6prefix
        | Type::Tlv
        | Type::Vsa
        | Type::Evs
        | Type::Extended
        | Type::LongExtended
        | Type::Struct => "WBytes",
    }
}

fn oid_literal(parts: &[u32]) -> String {
    let mut s = String::from("[");
    for (i, p) in parts.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        let _ = write!(s, "{p}u32");
    }
    s.push(']');
    s
}

fn type_literal(t: Type) -> &'static str {
    match t {
        Type::String => "super::Type::String",
        Type::Octets => "super::Type::Octets",
        Type::Ipaddr => "super::Type::Ipaddr",
        Type::Ipv6addr => "super::Type::Ipv6addr",
        Type::Ipv4prefix => "super::Type::Ipv4prefix",
        Type::Ipv6prefix => "super::Type::Ipv6prefix",
        Type::Byte => "super::Type::Byte",
        Type::Short => "super::Type::Short",
        Type::Integer => "super::Type::Integer",
        Type::Integer64 => "super::Type::Integer64",
        Type::Signed => "super::Type::Signed",
        Type::Date => "super::Type::Date",
        Type::Ifid => "super::Type::Ifid",
        Type::Ether => "super::Type::Ether",
        Type::Abinary => "super::Type::Abinary",
        Type::Tlv => "super::Type::Tlv",
        Type::Vsa => "super::Type::Vsa",
        Type::Evs => "super::Type::Evs",
        Type::Extended => "super::Type::Extended",
        Type::LongExtended => "super::Type::LongExtended",
        Type::Struct => "super::Type::Struct",
        Type::Uint32 => "super::Type::Uint32",
        // FixedOctets carries a length and is rendered separately by
        // the attribute writer.
        Type::FixedOctets(_) => unreachable!("FixedOctets handled inline"),
    }
}

fn flags_literal(f: Flags) -> String {
    let encrypt = match f.encrypt {
        Some(n) => format!("Some({n})"),
        None => "None".to_owned(),
    };
    format!(
        "super::Flags {{ encrypt: {encrypt}, has_tag: {tag}, concat: {concat}, array: {array}, virtual_: {virt}, internal: {internal}, secret: {secret} }}",
        tag = f.has_tag,
        concat = f.concat,
        array = f.array,
        virt = f.virtual_,
        internal = f.internal,
        secret = f.secret,
    )
}

fn estimate_capacity(dict: &Dictionary) -> usize {
    // Rough lower bound; saves repeated reallocations on the larger
    // generated files (RFC: ~1k attributes, vendor: several thousand).
    256 + dict.vendors.len() * 96 + dict.attributes.len() * 192 + dict.values.len() * 96
}

#[cfg(test)]
mod tests {
    use super::super::{Attribute, Dictionary, Flags, Oid, Type, Value, Vendor};
    use super::*;

    fn fixture() -> Dictionary {
        Dictionary {
            vendors: vec![Vendor {
                name: "Acme".into(),
                id: 99,
                type_len: 1,
                length_len: 1,
                has_continuation: false,
            }],
            attributes: vec![
                Attribute {
                    name: "User-Name".into(),
                    oid: Oid(vec![1]),
                    vendor: None,
                    typ: Type::String,
                    flags: Flags::default(),
                },
                Attribute {
                    name: "Acme-Token".into(),
                    oid: Oid(vec![1]),
                    vendor: Some(99),
                    typ: Type::Octets,
                    flags: Flags {
                        encrypt: Some(2),
                        has_tag: true,
                        ..Flags::default()
                    },
                },
            ],
            values: vec![Value {
                attribute: "Service-Type".into(),
                name: "Framed-User".into(),
                number: 2,
            }],
        }
    }

    #[test]
    fn render_is_deterministic() {
        let d = fixture();
        assert_eq!(render("test", &d), render("test", &d));
    }

    #[test]
    fn render_emits_expected_sections() {
        let s = render("test", &fixture());
        assert!(s.contains("pub static VENDORS"));
        assert!(s.contains("pub static ATTRIBUTES"));
        assert!(s.contains("pub static VALUES"));
        assert!(s.contains("name: \"Acme\""));
        assert!(s.contains("name: \"User-Name\""));
        assert!(s.contains("vendor: Some(99)"));
        assert!(s.contains("encrypt: Some(2)"));
        assert!(s.contains("has_tag: true"));
        assert!(s.contains("Framed-User"));
    }

    #[test]
    fn render_emits_typed_attrs_module() {
        let s = render("test", &fixture());
        // Module wrapper.
        assert!(s.contains("pub mod attrs"));
        // Top-level attribute → Attr<WText>.
        assert!(s.contains("pub const USER_NAME: Attr<WText> = Attr::new(1);"));
        // Vendor attribute → VsaAttr<WBytes> (octets); PEN + code in order.
        assert!(s.contains("pub const ACME_TOKEN: VsaAttr<WBytes> = VsaAttr::new(99, 1);"));
    }

    #[test]
    fn const_ident_normalizes_names() {
        assert_eq!(super::const_ident("User-Name"), "USER_NAME");
        assert_eq!(super::const_ident("Cisco-AVPair"), "CISCO_AVPAIR");
        assert_eq!(super::const_ident("MS-CHAP2-Response"), "MS_CHAP2_RESPONSE");
    }
}
