//! Renders a parsed [`Dictionary`] to a Rust source file consumed by
//! the `radius-dict` crate's `generated` module.
//!
//! Used by `build.rs` at compile time and by the in-tree determinism /
//! snapshot tests. Output is deterministic: the parser preserves source
//! order, this renderer is a pure function of its input, and no
//! timestamps or absolute paths leak in.

use std::fmt::Write;

use super::{Dictionary, Flags, Type};

/// Render `dict` to a string suitable for `include!()` inside a module
/// rooted one level below `crate::dict` (so `super::Type::Foo` resolves).
///
/// `module_label` is embedded in the file header comment for human
/// orientation and has no semantic effect.
#[must_use]
pub fn render(module_label: &str, dict: &Dictionary) -> String {
    let mut out = String::with_capacity(estimate_capacity(dict));

    writeln!(
        out,
        "// @generated by build.rs from FreeRADIUS dictionary group `{module_label}`."
    )
    .unwrap();
    writeln!(
        out,
        "// Do not edit by hand; rerun `cargo build` to refresh."
    )
    .unwrap();
    writeln!(out).unwrap();

    write_vendors(&mut out, dict);
    writeln!(out).unwrap();
    write_attributes(&mut out, dict);
    writeln!(out).unwrap();
    write_values(&mut out, dict);
    writeln!(out).unwrap();
    write_attrs_module(&mut out, dict);

    out
}

fn write_vendors(out: &mut String, dict: &Dictionary) {
    writeln!(out, "pub static VENDORS: &[VendorEntry] = &[").unwrap();
    for v in &dict.vendors {
        writeln!(
            out,
            "    VendorEntry {{ name: {name:?}, id: {id}, type_len: {type_len}, length_len: {length_len}, has_continuation: {cont} }},",
            name = v.name,
            id = v.id,
            type_len = v.type_len,
            length_len = v.length_len,
            cont = v.has_continuation,
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn write_attributes(out: &mut String, dict: &Dictionary) {
    writeln!(out, "pub static ATTRIBUTES: &[AttributeEntry] = &[").unwrap();
    for a in &dict.attributes {
        let vendor = match a.vendor {
            Some(v) => format!("Some({v})"),
            None => "None".to_owned(),
        };
        let typ = match a.typ {
            Type::FixedOctets(n) => format!("super::Type::FixedOctets({n})"),
            other => type_literal(other).to_owned(),
        };
        writeln!(
            out,
            "    AttributeEntry {{ name: {name:?}, oid: &{oid}, vendor: {vendor}, typ: {typ}, flags: {flags} }},",
            name = a.name,
            oid = oid_literal(&a.oid.0),
            flags = flags_literal(a.flags),
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn write_values(out: &mut String, dict: &Dictionary) {
    writeln!(out, "pub static VALUES: &[ValueEntry] = &[").unwrap();
    for v in &dict.values {
        writeln!(
            out,
            "    ValueEntry {{ attribute: {attr:?}, name: {name:?}, number: {n} }},",
            attr = v.attribute,
            name = v.name,
            n = v.number,
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

/// Emit `pub mod attrs { ... }` with one typed const per attribute.
///
/// Top-level attributes become `Attr<T>`; vendor attributes become
/// `VsaAttr<T>`. Children of `tlv`-typed parents (2-component OIDs,
/// e.g. `173.1`, `146.1`) become `TlvAttr<T>` (top-level parent) or
/// `VsaTlvAttr<T>` (vendor parent). Deeper nesting and children of
/// non-`tlv` parents (RFC 6929 `extended` / `long-extended`) are
/// skipped — those framings need a separate API. Each emitted const
/// inherits its `T` from the dictionary's wire type via
/// [`wire_marker`].
fn write_attrs_module(out: &mut String, dict: &Dictionary) {
    // Build a quick lookup so we can validate that a 2-component
    // child's parent is a `tlv` container before emitting a TLV
    // handle for it. Keyed by `(vendor, root_oid)` so non-vendor and
    // vendor namespaces don't collide.
    use std::collections::HashMap;
    let mut parents: HashMap<(Option<u32>, u32), Type> = HashMap::new();
    for a in &dict.attributes {
        if a.oid.0.len() == 1 {
            parents.insert((a.vendor, a.oid.0[0]), a.typ);
        }
    }

    writeln!(
        out,
        "/// Typed handles for every attribute in this dictionary group."
    )
    .unwrap();
    writeln!(out, "///").unwrap();
    writeln!(
        out,
        "/// Top-level attributes are exposed as `Attr<T>`; attributes inside a"
    )
    .unwrap();
    writeln!(
        out,
        "/// `BEGIN-VENDOR` block are exposed as `VsaAttr<T>`. TLV sub-attributes"
    )
    .unwrap();
    writeln!(
        out,
        "/// (children of a `tlv`-typed parent) are exposed as `TlvAttr<T>` or"
    )
    .unwrap();
    writeln!(
        out,
        "/// `VsaTlvAttr<T>`. Use them with `RawAttribute::get` / `get_vsa` /"
    )
    .unwrap();
    writeln!(
        out,
        "/// `get_tlv` / `get_vsa_tlv` (in `radius_tokio::attributes`)."
    )
    .unwrap();
    writeln!(
        out,
        "#[allow(missing_docs, unused_imports, clippy::wildcard_imports)]"
    )
    .unwrap();
    writeln!(out, "pub mod attrs {{").unwrap();
    writeln!(out, "    use crate::typed::*;").unwrap();
    writeln!(out).unwrap();
    for a in &dict.attributes {
        let ident = const_ident(&a.name);
        match a.oid.0.as_slice() {
            // Top-level attribute.
            [root] => {
                let Ok(code) = u8::try_from(*root) else {
                    continue;
                };
                let marker = wire_marker(a.typ, a.flags);
                match a.vendor {
                    None => writeln!(
                        out,
                        "    pub const {ident}: Attr<{marker}> = Attr::new({code});",
                    )
                    .unwrap(),
                    Some(pen) => writeln!(
                        out,
                        "    pub const {ident}: VsaAttr<{marker}> = VsaAttr::new({pen}, {code});",
                    )
                    .unwrap(),
                }
            }
            // 2-component child (`parent.child`). Emit only when the
            // parent is a `tlv` container; the `extended` /
            // `long-extended` framings (RFC 6929) are out of scope
            // for the current TLV walker.
            [parent_root, child_sub] => {
                let Ok(parent_code) = u8::try_from(*parent_root) else {
                    continue;
                };
                let Ok(child_code) = u8::try_from(*child_sub) else {
                    continue;
                };
                if parents.get(&(a.vendor, *parent_root)) != Some(&Type::Tlv) {
                    continue;
                }
                let marker = wire_marker(a.typ, a.flags);
                match a.vendor {
                    None => writeln!(
                        out,
                        "    pub const {ident}: TlvAttr<{marker}> = TlvAttr::new({parent_code}, {child_code});",
                    )
                    .unwrap(),
                    Some(pen) => writeln!(
                        out,
                        "    pub const {ident}: VsaTlvAttr<{marker}> = VsaTlvAttr::new({pen}, {parent_code}, {child_code});",
                    )
                    .unwrap(),
                }
            }
            // Deeper nesting (3+ components) — RFC 6929 extended
            // children. Out of scope for now.
            _ => {}
        }
    }
    writeln!(out, "}}").unwrap();
}

/// Convert a dictionary attribute name (`Cisco-AVPair`) into a Rust
/// constant identifier (`CISCO_AVPAIR`). Replaces `-` with `_` and
/// upper-cases ASCII letters; non-ASCII bytes pass through unchanged.
fn const_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        match ch {
            '-' => out.push('_'),
            c if c.is_ascii_lowercase() => out.push(c.to_ascii_uppercase()),
            c => out.push(c),
        }
    }
    out
}

/// Map a dictionary [`Type`] (plus its flags) to the codec wire-type
/// marker that decodes it.
///
/// Three shapes feed in here:
///
/// - **Encrypted** attributes (`encrypt=N`) carry a cipher-shaped
///   value (e.g. `User-Password`'s xor-MD5 stream, `Tunnel-Password`'s
///   `tag || salt || ciphertext`) that has no meaning as the parent
///   dictionary type. They map to [`WBytes`] so a typed `get(...)`
///   yields the raw octets and callers route plaintext through the
///   dedicated `Reply::add_*_password` helpers.
/// - **Tagged** attributes (`has_tag`, RFC 2868 §3) get the
///   tag-aware markers so consumers see a [`Tagged<V>`] view and
///   never have to peel the tag byte themselves.
/// - Everything else maps directly to its scalar marker; container /
///   variable-shape types fall back to [`WBytes`] until a TLV walker
///   lands.
fn wire_marker(t: Type, flags: Flags) -> &'static str {
    // Encrypted attributes ship cipher-shaped values that don't match
    // the source dictionary type. Force raw octets so callers route
    // through the dedicated decrypt helpers (e.g. add_tunnel_password)
    // instead of UTF-8-decoding ciphertext.
    if flags.encrypt.is_some() {
        return "WBytes";
    }
    if flags.has_tag {
        return match t {
            Type::String => "WTaggedText",
            Type::Integer | Type::Uint32 | Type::Date => "WTaggedInteger",
            // No other RFC-defined types currently combine with
            // `has_tag`; fall through to raw octets if a dictionary
            // surprises us so we don't silently strip a tag byte.
            _ => "WBytes",
        };
    }
    match t {
        Type::String => "WText",
        Type::Byte => "WByte",
        Type::Short => "WShort",
        Type::Integer | Type::Uint32 | Type::Date => "WInteger",
        Type::Integer64 => "WInteger64",
        Type::Signed => "WSigned",
        Type::Ipaddr => "WIpv4",
        Type::Ipv6addr => "WIpv6",
        Type::Ether => "WEther",
        Type::Ifid => "WIfid",
        // Container / variable-shape types decode as raw octets for now.
        Type::Octets
        | Type::FixedOctets(_)
        | Type::Abinary
        | Type::Ipv4prefix
        | Type::Ipv6prefix
        | Type::Tlv
        | Type::Vsa
        | Type::Evs
        | Type::Extended
        | Type::LongExtended
        | Type::Struct => "WBytes",
    }
}

fn oid_literal(parts: &[u32]) -> String {
    let mut s = String::from("[");
    for (i, p) in parts.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        let _ = write!(s, "{p}u32");
    }
    s.push(']');
    s
}

fn type_literal(t: Type) -> &'static str {
    match t {
        Type::String => "super::Type::String",
        Type::Octets => "super::Type::Octets",
        Type::Ipaddr => "super::Type::Ipaddr",
        Type::Ipv6addr => "super::Type::Ipv6addr",
        Type::Ipv4prefix => "super::Type::Ipv4prefix",
        Type::Ipv6prefix => "super::Type::Ipv6prefix",
        Type::Byte => "super::Type::Byte",
        Type::Short => "super::Type::Short",
        Type::Integer => "super::Type::Integer",
        Type::Integer64 => "super::Type::Integer64",
        Type::Signed => "super::Type::Signed",
        Type::Date => "super::Type::Date",
        Type::Ifid => "super::Type::Ifid",
        Type::Ether => "super::Type::Ether",
        Type::Abinary => "super::Type::Abinary",
        Type::Tlv => "super::Type::Tlv",
        Type::Vsa => "super::Type::Vsa",
        Type::Evs => "super::Type::Evs",
        Type::Extended => "super::Type::Extended",
        Type::LongExtended => "super::Type::LongExtended",
        Type::Struct => "super::Type::Struct",
        Type::Uint32 => "super::Type::Uint32",
        // FixedOctets carries a length and is rendered separately by
        // the attribute writer.
        Type::FixedOctets(_) => unreachable!("FixedOctets handled inline"),
    }
}

fn flags_literal(f: Flags) -> String {
    let encrypt = match f.encrypt {
        Some(n) => format!("Some({n})"),
        None => "None".to_owned(),
    };
    format!(
        "super::Flags {{ encrypt: {encrypt}, has_tag: {tag}, concat: {concat}, array: {array}, virtual_: {virt}, internal: {internal}, secret: {secret} }}",
        tag = f.has_tag,
        concat = f.concat,
        array = f.array,
        virt = f.virtual_,
        internal = f.internal,
        secret = f.secret,
    )
}

fn estimate_capacity(dict: &Dictionary) -> usize {
    // Rough lower bound; saves repeated reallocations on the larger
    // generated files (RFC: ~1k attributes, vendor: several thousand).
    256 + dict.vendors.len() * 96 + dict.attributes.len() * 192 + dict.values.len() * 96
}

#[cfg(test)]
mod tests {
    use super::super::{Attribute, Dictionary, Flags, Oid, Type, Value, Vendor};
    use super::*;

    fn fixture() -> Dictionary {
        Dictionary {
            vendors: vec![Vendor {
                name: "Acme".into(),
                id: 99,
                type_len: 1,
                length_len: 1,
                has_continuation: false,
            }],
            attributes: vec![
                Attribute {
                    name: "User-Name".into(),
                    oid: Oid(vec![1]),
                    vendor: None,
                    typ: Type::String,
                    flags: Flags::default(),
                },
                Attribute {
                    name: "Acme-Token".into(),
                    oid: Oid(vec![1]),
                    vendor: Some(99),
                    typ: Type::Octets,
                    flags: Flags {
                        encrypt: Some(2),
                        has_tag: true,
                        ..Flags::default()
                    },
                },
            ],
            values: vec![Value {
                attribute: "Service-Type".into(),
                name: "Framed-User".into(),
                number: 2,
            }],
        }
    }

    #[test]
    fn render_is_deterministic() {
        let d = fixture();
        assert_eq!(render("test", &d), render("test", &d));
    }

    #[test]
    fn render_emits_expected_sections() {
        let s = render("test", &fixture());
        assert!(s.contains("pub static VENDORS"));
        assert!(s.contains("pub static ATTRIBUTES"));
        assert!(s.contains("pub static VALUES"));
        assert!(s.contains("name: \"Acme\""));
        assert!(s.contains("name: \"User-Name\""));
        assert!(s.contains("vendor: Some(99)"));
        assert!(s.contains("encrypt: Some(2)"));
        assert!(s.contains("has_tag: true"));
        assert!(s.contains("Framed-User"));
    }

    #[test]
    fn render_emits_typed_attrs_module() {
        let s = render("test", &fixture());
        // Module wrapper.
        assert!(s.contains("pub mod attrs"));
        // Top-level attribute → Attr<WText>.
        assert!(s.contains("pub const USER_NAME: Attr<WText> = Attr::new(1);"));
        // Vendor attribute → VsaAttr<WBytes> (octets); PEN + code in order.
        assert!(s.contains("pub const ACME_TOKEN: VsaAttr<WBytes> = VsaAttr::new(99, 1);"));
    }

    #[test]
    fn const_ident_normalizes_names() {
        assert_eq!(super::const_ident("User-Name"), "USER_NAME");
        assert_eq!(super::const_ident("Cisco-AVPair"), "CISCO_AVPAIR");
        assert_eq!(super::const_ident("MS-CHAP2-Response"), "MS_CHAP2_RESPONSE");
    }

    #[test]
    fn tagged_attributes_get_tagged_markers() {
        let d = Dictionary {
            vendors: vec![],
            attributes: vec![
                Attribute {
                    name: "Tunnel-Type".into(),
                    oid: Oid(vec![64]),
                    vendor: None,
                    typ: Type::Integer,
                    flags: Flags {
                        has_tag: true,
                        ..Flags::default()
                    },
                },
                Attribute {
                    name: "Tunnel-Client-Endpoint".into(),
                    oid: Oid(vec![66]),
                    vendor: None,
                    typ: Type::String,
                    flags: Flags {
                        has_tag: true,
                        ..Flags::default()
                    },
                },
                // `has_tag,encrypt=2` — encryption wins; the typed handle
                // exposes raw octets so callers go through the dedicated
                // tunnel-password helper instead.
                Attribute {
                    name: "Tunnel-Password".into(),
                    oid: Oid(vec![69]),
                    vendor: None,
                    typ: Type::String,
                    flags: Flags {
                        has_tag: true,
                        encrypt: Some(2),
                        ..Flags::default()
                    },
                },
            ],
            values: vec![],
        };
        let s = render("test", &d);
        assert!(s.contains("pub const TUNNEL_TYPE: Attr<WTaggedInteger>"));
        assert!(s.contains("pub const TUNNEL_CLIENT_ENDPOINT: Attr<WTaggedText>"));
        assert!(s.contains("pub const TUNNEL_PASSWORD: Attr<WBytes>"));
    }

    #[test]
    fn tlv_children_emit_typed_handles() {
        let d = Dictionary {
            vendors: vec![Vendor {
                name: "Ruckus".into(),
                id: 25053,
                type_len: 1,
                length_len: 1,
                has_continuation: false,
            }],
            attributes: vec![
                // Top-level `tlv` parent (RFC 6930 IPv6-6rd-Configuration).
                Attribute {
                    name: "IPv6-6rd-Configuration".into(),
                    oid: Oid(vec![173]),
                    vendor: None,
                    typ: Type::Tlv,
                    flags: Flags::default(),
                },
                // Child of the top-level parent.
                Attribute {
                    name: "IPv6-6rd-IPv4MaskLen".into(),
                    oid: Oid(vec![173, 1]),
                    vendor: None,
                    typ: Type::Integer,
                    flags: Flags::default(),
                },
                // Vendor TLV parent.
                Attribute {
                    name: "Ruckus-TC-Attr-Ids-With-Quota".into(),
                    oid: Oid(vec![146]),
                    vendor: Some(25053),
                    typ: Type::Tlv,
                    flags: Flags::default(),
                },
                // Vendor TLV child.
                Attribute {
                    name: "Ruckus-TC-Name-Quota".into(),
                    oid: Oid(vec![146, 1]),
                    vendor: Some(25053),
                    typ: Type::String,
                    flags: Flags::default(),
                },
                // Child of a non-tlv parent — must be skipped.
                Attribute {
                    name: "Skip-Me".into(),
                    oid: Oid(vec![200]),
                    vendor: None,
                    typ: Type::Extended,
                    flags: Flags::default(),
                },
                Attribute {
                    name: "Skip-Me-Child".into(),
                    oid: Oid(vec![200, 1]),
                    vendor: None,
                    typ: Type::Integer,
                    flags: Flags::default(),
                },
            ],
            values: vec![],
        };
        let s = render("test", &d);
        // Top-level TLV child gets a `TlvAttr<T>`.
        assert!(
            s.contains("pub const IPV6_6RD_IPV4MASKLEN: TlvAttr<WInteger> = TlvAttr::new(173, 1);")
        );
        // Vendor TLV child gets a `VsaTlvAttr<T>` carrying PEN +
        // parent type + child sub-type.
        assert!(s.contains(
            "pub const RUCKUS_TC_NAME_QUOTA: VsaTlvAttr<WText> = VsaTlvAttr::new(25053, 146, 1);"
        ));
        // Children of non-`tlv` parents (e.g. `extended`) are not
        // emitted yet.
        assert!(
            !s.contains("SKIP_ME_CHILD"),
            "non-tlv extended children must be skipped",
        );
    }
}
